### ISSUE TITLE
Scope topics with `input` and `output`

### ISSUE THREAD

**Issue by adamlm** [the-hive-lab/dwm1001_ros2#43]
To improve in-code and in-configuration documentation, the topic names should be prepended with `~/input` and `~output` by default. The topic names can be changed with ROS 2 topic remapping. This is similar to how the autoware.universe structures their ROS 2 packages. See [here](https://autowarefoundation.github.io/autoware.universe/main/planning/behavior_path_planner/#inputs-outputs-api) for an example.

**Comment by drpjm** [comment]
Closed with recent PR #51
